[package]
name = "wollok-ast"
version = "0.1.0"
edition = "2024"

[dependencies]
wollok-lexer.path = "../wollok-lexer"
wollok-common.path = "../wollok-common"
ariadne.workspace = true
tracing.workspace = true
owo-colors.workspace = true
