name: Quality Gate

on:
  pull_request:
      branches:
          main
  push:
      branches:
          main

  workflow_call:
    inputs:
      runs-on:
        default: ubuntu-latest
        required: false
        type: string
      checks-command:
        default: "--all --check"
        required: false
        type: string
      clippy-command:
        default: "-- --warn clippy::pedantic -D warnings"
        required: false
        type: string
      tests-command:
        default: "test --workspace --lib"
        required: false
        type: string

jobs:
    check-format:
        uses: ./.github/workflows/format.yml
        with:
          name: Checks
          runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}
          command: ${{ inputs.checks-command || '--all --check' }}

    check-clippy:
        needs: [check-format]
        uses: ./.github/workflows/clippy.yml
        with:
          name: Clippy
          runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}
          command: ${{ inputs.clippy-command || '-- --warn clippy::pedantic -D warnings' }}

    check-tests:
        needs: [check-clippy]
        uses: ./.github/workflows/tests.yml
        with:
          name: Tests
          runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}
          command: ${{ inputs.tests-command || 'test --workspace --lib' }}