name: Clippy

on:
  workflow_call:
    inputs:
      runs-on:
        default: ubuntu-latest
        required: false
        type: string
      name:
        default: Clippy
        required: false
        type: string
      command:
        default: "-- -D warnings"
        required: true
        type: string

jobs:
  check-fmt:
    name: ${{ inputs.name }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
      - name: ${{ inputs.name }}
        run: |
          cargo clippy ${{ inputs.command }}